export const RECEIVE_AUTHENTICATION_DATA = "RECEIVE_AUTHENTICATION_DATA";
export const RECEIVE_LOGOUT_REQUEST = "RECEIVE_LOGOUT_REQUEST";

export const SAVE_AUDIO = "SAVE_AUDIO";
export const RECEIVE_TRANSCRIPTION_DATA = "RECEIVE_TRANSCRIPTION_DATA";

export const RECEIVE_REQUEST_ERRORS = "RECEIVE_REQUEST_ERRORS";